apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: logging-service
  name: logging-service
spec:
  ports:
  - name: "8084"
    port: 8084
    targetPort: 8084
  selector:
    io.kompose.service: logging-service
status:
  loadBalancer: {}
