version: '3'
services:
  mony-queue:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  logging-db:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mony
    volumes:
      - /data/db

  caching-db:
    image: redis:5
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./database/redis-db:/data

  account-service-database:
    image: mysql:8.0.13
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account-service
    volumes:
      - ./database/account-service:/var/lib/mysql

  loan-service-database:
    image: mysql:8.0.13
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loan-service
    volumes:
      - ./database/loan-service:/var/lib/mysql

  loan-application-service-database:
    image: mysql:8.0.13
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3308:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loan-application-service
    volumes:
      - ./database/loan-application-service:/var/lib/mysql

  scoring-service-database:
    image: mariadb:10
    ports:
      - 3309:3306
    restart: always
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scoring_service
    volumes:
      - ./database/scoring-service-database:/var/lib/mysql

  identity-service-database:
    image: mariadb:10
    ports:
      - 3310:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity_service
    volumes:
      - ./database/identity-service-database:/var/lib/mysql
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON --character-set-server=utf8 --collation-server=utf8_unicode_ci

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 8079:8079
    environment:
      NOTIFICATION_SERVICE: http://im-service:8080
      ACCOUNT_SERVICE: http://account-service:8081
      LOAN_SERVICE: http://loan-service:8082
      LOAN_APPLICATION_SERVICE: http://loan-application-service:8083
      LOGGING_SERVICE: http://logging-service:8084
      IDENTITY_SERVICE: http://identity-service:8086

  im-service:
    build:
      context: ./im-service
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      API_GATEWAY_URL: http://api-gateway:8079
    ports:
      - 8080:8080
    depends_on:
      - api-gateway

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 8081:8081
    environment:
      DATABASE_SOURCE: jdbc:mysql://account-service-database:3306/account-service
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      API_GATEWAY_URL: http://api-gateway:8079
      IM_SERVICE: http://im-service:8080
      IM_SERVICE_CALLBACK: http://account-service:8081
      LOAN_SERVICE: http://loan-service:8082
      SCORING_SERVICE: http://scoring-service:8085
      IDENTITY_SERVICE: http://identity-service:8086
      RABBIT_HOST: mony-queue
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
    depends_on:
      - account-service-database
      - im-service
      - api-gateway

  loan-service:
    build:
      context: ./loan-service
      dockerfile: Dockerfile.prod
    ports:
      - 8082:8082
    restart: always
    environment:
      DATABASE_SOURCE: jdbc:mysql://loan-service-database:3306/loan-service
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      API_GATEWAY_URL: http://api-gateway:8079
      IM_SERVICE: http://im-service:8080
      ACCOUNT_SERVICE: http://account-service:8081
      LOAN_APPLICATION_SERVICE: http://loan-application-service:8083
      IM_SERVICE_CALLBACK: http://loan-service:8082
      SELF_SERVICE: http://loan-service:8082
      IDENTITY_SERVICE: http://identity-service:8086
      REDIS_HOST: caching-db
      REDIS_PORT: 6379
      RABBIT_HOST: mony-queue
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - loan-service-database
      - account-service
      - im-service
      - api-gateway

  loan-application-service:
    build:
      context: ./loan-application-service
      dockerfile: Dockerfile.prod
    ports:
      - 8083:8083
    restart: always
    environment:
      DATABASE_SOURCE: jdbc:mysql://loan-application-service-database:3306/loan-application-service
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      API_GATEWAY_URL: http://api-gateway:8079
      IM_SERVICE: http://im-service:8080
      ACCOUNT_SERVICE: http://account-service:8081
      LOAN_SERVICE: http://loan-service:8082
      IM_SERVICE_CALLBACK: http://loan-application-service:8083
      SELF_SERVICE: http://loan-application-service:8083
    depends_on:
      - loan-application-service-database
      - im-service
      - account-service
      - loan-service
      - api-gateway

  logging-service:
    build:
      context: ./logging-service
      dockerfile: Dockerfile.prod
    ports:
      - 8084:8084
    restart: always
    environment:
      DATABASE_SOURCE: jdbc:mysql://loan-service-database:3306/loan-service
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      API_GATEWAY_URL: http://api-gateway:8079
      MONGO_HOST: logging-db
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASSWORD: root
      RABBIT_HOST: mony-queue
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
    depends_on:
      - loan-service-database
      - mony-queue
      - logging-db

  scoring-service:
    build:
      context: ./scoring-service
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 8085:8085
    environment:
      DATABASE_SOURCE: jdbc:mariadb://scoring-service-database:3309/scoring_service
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      API_GATEWAY_URL: http://api-gateway:8079
      MONGO_HOST: logging-db
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASSWORD: root
      MONGO_DATABASE: ascore-raw
      MONGO_AUTH: admin
    depends_on:
      - scoring-service-database
      - logging-db
      - api-gateway

  identity-service:
    build:
      context: ./identity-service
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 8086:8086
    environment:
      DATABASE_SOURCE: jdbc:mariadb://scoring-service-database:3310/identity_service
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      API_GATEWAY_URL: http://api-gateway:8079
    depends_on:
      - identity-service-database
      - api-gateway

  admin-cp:
    build:
      context: ./admin-cp
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    restart: always