version: '3'
services:
  account-service-database:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account-service
    volumes:
      - ./database/account-service:/var/lib/mysql

  loan-service-database:
    image: mysql:5.7.22
    ports:
      - 3307:3306
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loan-service
    volumes:
      - ./database/loan-service:/var/lib/mysql

  loan-application-service-database:
    image: mysql:5.7.22
    ports:
      - 3308:3306
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loan-application-service
    volumes:
      - ./database/loan-application-service:/var/lib/mysql

  logging-db:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mony
    volumes:
    - /data/db

  caching-db:
    image: redis
    restart: always
    ports:
    - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf