version: '3'
services:
  # im-service:
  #   build: ./im-service
  #   ports:
  #     - 8081:8080
      
  account-service-database:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: p2plending
    volumes:
      - /var/lib/mysql

  account-service:
    build: ./account-service
    ports:
      - 8080:8080
    depends_on: 
      - account-service-database