version: '3'
services:
  lending-platform-database:
    image: mariadb:10.4
    ports:
      - 3305:3306
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci --event-scheduler=ON
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lending-platform
    volumes:
      - ./database/lending-platform:/var/lib/mysql

  logging-db:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mony
    volumes:
      - /data/db

  caching-db:
    image: redis:5.0
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./database/redis-db:/data

  mony-queue:
    image: rabbitmq:3.7-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411