version: '3'
services:
  account-service-database:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account-service
    volumes:
      - ./database/account-service:/var/lib/mysql

  loan-service-database:
    image: mysql:5.7.22
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loan-service
    volumes:
      - ./database/loan-service:/var/lib/mysql

  loan-application-service-database:
    image: mysql:5.7.22
    ports:
      - 3308:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loan-application-service
    volumes:
      - ./database/loan-application-service:/var/lib/mysql