version: '3'
services:
  account-service-database:
    image: mysql:8.0.13
    ports:
      - 3306:3306
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account-service
    volumes:
      - ./database/account-service:/var/lib/mysql

  loan-service-database:
    image: mysql:8.0.13
    ports:
      - 3307:3306
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loan-service
    volumes:
      - ./database/loan-service:/var/lib/mysql

  loan-application-service-database:
    image: mysql:8.0.13
    ports:
      - 3308:3306
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loan-application-service
    volumes:
      - ./database/loan-application-service:/var/lib/mysql

  scoring-service-database:
    image: mariadb:10
    ports:
      - 3309:3306
    restart: always
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scoring_service
    volumes:
      - ./database/scoring-service-database:/var/lib/mysql

  identity-service-database:
    image: mariadb:10
    ports:
    - 3310:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity_service
    volumes:
    - ./database/identity-service-database:/var/lib/mysql
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON --character-set-server=utf8 --collation-server=utf8_unicode_ci

  logging-db:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mony
    volumes:
      - /data/db
  
  caching-db:
    image: redis:5
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./database/redis-db:/data

  mony-queue:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
