version: '3'
services:
  im-service:
    build: ./im-service
    ports:
      - 8081:8080
      
  account-service-database:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: p2plending
    volumes:
      - /var/lib/mysql

  account-service:
    build: ./account-service
    ports:
      - 8081:8080
    environment:
      DATABASE_HOST: account-service-database
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE: p2plending
    depends_on: 
      - account-service-database
      - im-service

  # loan-service-database:
  #   image: mysql:5.7.22
  #   ports:
  #     - 330:3306
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: p2plending
  #   volumes:
  #     - /var/lib/mysql

  # loan-service:
  #   build: ./loan-service
  #   ports:
  #     - 8082:8080
  #   depends_on: 
  #     - loan-service-database
  #     - im-service
