apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml -o k8s/prod/
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
      - env:
        - name: ACCOUNT_SERVICE
          value: http://account-service:8081
        - name: IDENTITY_SERVICE
          value: http://identity-service:8086
        - name: LOAN_APPLICATION_SERVICE
          value: http://loan-service:8083
        - name: LOAN_SERVICE
          value: http://loan-service:8082
        - name: LOGGING_SERVICE
          value: http://logging-service:8084
        - name: NOTIFICATION_SERVICE
          value: http://im-service:8080
        - name: SCORING_SERVICE
          value: http://scoring-service:8085
        image: api-gateway
        name: api-gateway
        ports:
        - containerPort: 8079
        resources: {}
      restartPolicy: Always
status: {}
