apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\docker-compose.prod.yml -o k8s
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: account-service
  name: account-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: account-service
    spec:
      containers:
      - env:
        - name: API_GATEWAY_URL
          value: http://api-gateway:8079
        - name: DATABASE_PASSWORD
          value: root
        - name: DATABASE_SOURCE
          value: jdbc:mysql://account-service-database:3306/account-service?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
        - name: DATABASE_USER
          value: root
        - name: IM_SERVICE
          value: http://im-service:8080
        - name: IM_SERVICE_CALLBACK
          value: http://account-service:8081
        - name: LOAN_SERVICE
          value: http://loan-service:8082
        image: account-service
        name: account-service
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
