apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\docker-compose.prod.yml -o k8s
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: account-service-database
  name: account-service-database
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: account-service-database
    spec:
      containers:
      - args:
        - mysqld
        - --default-authentication-plugin=mysql_native_password
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
        env:
        - name: MYSQL_DATABASE
          value: account-service
        - name: MYSQL_ROOT_PASSWORD
          value: root
        image: mysql:8.0.13
        name: account-service-database
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
