apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -o k8s
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
      - env:
        - name: ACCOUNT_SERVICE
          value: http://account-service:8080
        - name: LOAN_APPLICATION_SERVICE
          value: http://loan-application-service:8080
        - name: LOAN_SERVICE
          value: http://loan-service:8080
        - name: NOTIFICATION_SERVICE
          value: http://im-service:8080
        image: api-gateway
        name: api-gateway
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
