apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\docker-compose.prod.yml -o k8s
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: identity-service
  name: identity-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: identity-service
    spec:
      containers:
      - env:
        - name: API_GATEWAY_URL
          value: http://api-gateway:8079
        - name: DATABASE_PASSWORD
          value: root
        - name: DATABASE_SOURCE
          value: jdbc:mariadb://identity-service-database:3310/identity_service
        - name: DATABASE_USER
          value: root
        image: identity-service
        name: identity-service
        ports:
        - containerPort: 8086
        resources: {}
      restartPolicy: Always
status: {}
