apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -o k8s
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: loan-application-service-database
  name: loan-application-service-database
spec:
  ports:
  - name: "3308"
    port: 3308
    targetPort: 3306
  selector:
    io.kompose.service: loan-application-service-database
status:
  loadBalancer: {}
