apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\docker-compose.prod.yml -o .\k8s\
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: loan-service
  name: loan-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: loan-service
    spec:
      containers:
      - env:
        - name: ACCOUNT_SERVICE
          value: http://account-service:8081
        - name: API_GATEWAY_URL
          value: http://api-gateway:8079
        - name: DATABASE_PASSWORD
          value: root
        - name: DATABASE_SOURCE
          value: jdbc:mysql://loan-service-database:3306/loan-service?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
        - name: DATABASE_USER
          value: root
        - name: IM_SERVICE
          value: http://im-service:8080
        - name: IM_SERVICE_CALLBACK
          value: http://loan-service:8082
        - name: LOAN_APPLICATION_SERVICE
          value: http://loan-application-service:8083
        - name: SELF_SERVICE
          value: http://loan-service:8082
        image: loan-service
        name: loan-service
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
status: {}
