apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\docker-compose.prod.yml -o k8s
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: logging-service
  name: logging-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: logging-service
    spec:
      containers:
      - env:
        - name: DATABASE_PASSWORD
          value: root
        - name: DATABASE_SOURCE
          value: jdbc:mysql://loan-service-database:3306/loan-service
        - name: DATABASE_USER
          value: root
        - name: MONGO_HOST
          value: logging-db
        - name: MONGO_PASSWORD
          value: root
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USER
          value: root
        - name: RABBIT_HOST
          value: mony-queue
        - name: RABBIT_PASSWORD
          value: guest
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: guest
        image: logging-service
        name: logging-service
        ports:
        - containerPort: 8084
        resources: {}
      restartPolicy: Always
status: {}
