apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\docker-compose.prod.yml -o k8s
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: scoring-service-database
  name: scoring-service-database
spec:
  ports:
  - name: "3309"
    port: 3309
    targetPort: 3306
  selector:
    io.kompose.service: scoring-service-database
status:
  loadBalancer: {}
