apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\docker-compose.prod.yml -o k8s
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: scoring-service
  name: scoring-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: scoring-service
    spec:
      containers:
      - env:
        - name: DATABASE_PASSWORD
          value: root
        - name: DATABASE_SOURCE
          value: jdbc:mariadb://scoring-service-database:3309/scoring_service
        - name: DATABASE_USER
          value: root
        - name: MONGO_AUTH
          value: admin
        - name: MONGO_DATABASE
          value: ascore-raw
        - name: MONGO_HOST
          value: logging-db
        - name: MONGO_PASSWORD
          value: root
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USER
          value: root
        image: scoring-service
        name: scoring-service
        ports:
        - containerPort: 8085
        resources: {}
      restartPolicy: Always
status: {}
