apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.staging.yml -o k8s/staging/
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: payment-service
  name: payment-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: payment-service
    spec:
      containers:
      - env:
        - name: API_GATEWAY_URL
          value: http://api-gateway:8079
        image: payment-service
        name: payment-service
        ports:
        - containerPort: 8089
        resources: {}
      restartPolicy: Always
status: {}
